version: '3.4'

services:
  react:
    container_name: react
    build:
      context: .
      dockerfile: ./apps/react/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - portabl
    volumes:
      - /app/node_modules

  javascript:
    container_name: javascript
    build:
      context: .
      dockerfile: ./apps/javascript/Dockerfile
    restart: always
    tty: true
    ports:
      - 3000:80
    networks:
      - portabl
    volumes:
      - /app/node_modules

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - portabl
    volumes:
      - /app/node_modules

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  portabl:
    name: portabl
